export const workPackagesLocators = {
  createButton:'.wp-create-button',
  packageTypesContainer: '#types-context-menu',
  taskTypeOption: 'Task',
  errorMessageToaster:'.op-toast--wrapper',
  createNewWorkPackageButton: 'Create new work package',
  newRowInTable: '#wp-row-new-table',
  taskNameInputFromTable: '#wp-new-inline-edit--field-subject',
  packageTypeInputFromTable: '#wp-new-inline-edit--field-type',
  packageTypesContainerFromTable: '.ng-dropdown-panel-items.scroll-host',
  taskTypeOptionFromTable: '.ng-option.ng-option-marked',
  projectInputFromTable: '//ng-select[@id="" and contains(@class, "ng-select-typeahead")]',
  projectContainerFromTable: 'Options List',
  workPackageModuleProjectOption: 'Package Module Project',
  workPackagesToolbar: '.toolbar-items.hide-when-print',
  filterButton: '#work-packages-filter-toggle-button',
  filterByTextInput: '#filter-by-text-input',
  firstRowInTable: '.results-tbody tr',
  titleRowInTable: '.wp-table--cell-td.subject.-max.-with-hierarchy',
  firstRowThreePoints: '.icon.icon-show-more-horizontal',
  moveToAnotherProjectOption: '.icon-action-menu.icon-move',
  deletePackageOption: '.icon-action-menu.icon-delete',
  deleteOption: 'Delete',
  deleteModal: '#wp_destroy_modal',
  deleteConfirmButton: 'Delete',
  generatePDFOption: '.icon-action-menu.icon-export-pdf-with-descriptions',
  generatePDFModal: '#op-work-package-generate-pdf-dialog',
  downloadPDFButton: 'Download',
  successUpdateToaster: '.Banner.flash.Banner--success.flash-success',
  successDeleteToaster: '.op-toast--wrapper',
};
